name: Trigger auto deployment for webhook

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '"./Dockerfile"/**'
    - '.github/workflows/webhook-AutoDeployTrigger-84db4fc4-2f11-40ae-86d7-841391bf198e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBHOOK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBHOOK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBHOOK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}"./Dockerfile" 
          registryUrl: tppregistry1.azurecr.io
          registryUsername: ${{ secrets.WEBHOOK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBHOOK_REGISTRY_PASSWORD }}
          containerAppName: webhook
          resourceGroup: ukgwebhooksite
          imageToBuild: tppregistry1.azurecr.io/webhook:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


